In [1]:
import pandas as pd
import itertools

In [2]:
crimes = pd.read_csv("aggregated.csv")

In [3]:
crimes.head(n=5)

,Unnamed: 0,State,Year,Murder,Rape,Foeticide,Kidnapping and Abduction,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total
0,0,andhra pradesh,2001,19.0,12.0,0.0,29.0,6.0,0.0,0.0,0.0,0.0,0.0,66.0
1,1,andhra pradesh,2001,2.0,0.0,0.0,0.0,0.0,19.0,2.0,0.0,2.0,0.0,25.0
2,2,andhra pradesh,2001,2.0,15.0,0.0,2.0,0.0,3.0,4.0,0.0,0.0,1.0,27.0
3,3,andhra pradesh,2001,1.0,34.0,0.0,16.0,0.0,0.0,3.0,0.0,0.0,0.0,54.0
4,4,andhra pradesh,2001,5.0,9.0,0.0,6.0,1.0,0.0,1.0,0.0,4.0,40.0,66.0

In [4]:
sum_crimes = []
for i in range(3,13):
    sumi=0
    for j in range(len(crimes)):
        sumi+=crimes.iloc[j][i]
    sum_crimes.append(sumi)
sum_crimes

[22426.0,
 94502.0,
 1694.0,
 196638.0,
 880.0,
 12504.0,
 10413.0,
 1063.0,
 1916.0,
 98348.0]

In [5]:
for i in range(len(crimes)):
    for j in range(3,13):
        x=5
        #print(crimes.iloc[i][j], sum_crimes[j-3])
        crimes.iat[i,j]=crimes.iat[i,j]/sum_crimes[j-3]
crimes.head(n=5)

,Unnamed: 0,State,Year,Murder,Rape,Foeticide,Kidnapping and Abduction,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total
0,0,andhra pradesh,2001,0.000847,0.000127,0.0,0.000147,0.006818,0.00000,0.000000,0.0,0.000000,0.000000,66.0
1,1,andhra pradesh,2001,0.000089,0.000000,0.0,0.000000,0.000000,0.00152,0.000192,0.0,0.001044,0.000000,25.0
2,2,andhra pradesh,2001,0.000089,0.000159,0.0,0.000010,0.000000,0.00024,0.000384,0.0,0.000000,0.000010,27.0
3,3,andhra pradesh,2001,0.000045,0.000360,0.0,0.000081,0.000000,0.00000,0.000288,0.0,0.000000,0.000000,54.0
4,4,andhra pradesh,2001,0.000223,0.000095,0.0,0.000031,0.001136,0.00000,0.000096,0.0,0.002088,0.000407,66.0

In [6]:
crimes = crimes.drop(['State', 'Year'], axis=1)

In [7]:
crimes.head(n=10)

,Unnamed: 0,Murder,Rape,Foeticide,Kidnapping and Abduction,Abetment of suicide,Exposure and abandonment,Procuration of minor girls,Selling of girls for prostitution,Prohibition of child marriage act,Other Crimes,Total
0,0,0.000847,0.000127,0.0,0.000147,0.006818,0.00000,0.000000,0.0,0.000000,0.000000,66.0
1,1,0.000089,0.000000,0.0,0.000000,0.000000,0.00152,0.000192,0.0,0.001044,0.000000,25.0
2,2,0.000089,0.000159,0.0,0.000010,0.000000,0.00024,0.000384,0.0,0.000000,0.000010,27.0
3,3,0.000045,0.000360,0.0,0.000081,0.000000,0.00000,0.000288,0.0,0.000000,0.000000,54.0
4,4,0.000223,0.000095,0.0,0.000031,0.001136,0.00000,0.000096,0.0,0.002088,0.000407,66.0
5,5,0.000223,0.000085,0.0,0.000020,0.000000,0.00000,0.000000,0.0,0.000000,0.000061,23.0
6,6,0.000045,0.000063,0.0,0.000000,0.000000,0.00000,0.000192,0.0,0.000000,0.000000,9.0
7,7,0.000000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0
8,8,0.000000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0
9,9,0.000000,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0

In [8]:
freq_itemsets = []
freq_itemsets.append([[i] for i in range(1,11)])
freq_itemsets

[[[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]]]

In [9]:
sup = {}
for i in range(1,11):
    sup[tuple([i])]=1
sup

{(1,): 1,
 (2,): 1,
 (3,): 1,
 (4,): 1,
 (5,): 1,
 (6,): 1,
 (7,): 1,
 (8,): 1,
 (9,): 1,
 (10,): 1}

In [10]:
def has_infrequent_subset(kitemset,kplusone_item, k):
    kitems=list(itertools.combinations(kplusone_item, k+1))
    kitems=[list(a) for a in kitems]
    for kitem in kitems:
        if kitem not in kitemset:
            return 1
    return 0

In [11]:
def apriori_gen(kitemset,k):
    pos_kplusone_itemset = []
    for i in range(len(kitemset)):
        for j in range(i+1,len(kitemset)):
            kplusone_item = list(set(kitemset[i]).union(set(kitemset[j])))
            if(len(kplusone_item)==k+2):
                flag=has_infrequent_subset(kitemset,kplusone_item, k)
                if(flag==0):
                    pos_kplusone_itemset.append(kplusone_item)
    
    pos_kplusone_itemset = set(tuple(sorted(sub)) for sub in pos_kplusone_itemset)
    pos_kplusone_itemset = [list(i) for i in pos_kplusone_itemset]
    return pos_kplusone_itemset

In [12]:
def apriori(min_sup):
    k=0
    while(1):
        kplusone_itemset = []
        kitemset = freq_itemsets[k]
        pos_kplusone_itemset = apriori_gen(kitemset,k)
        for kplusone_item in pos_kplusone_itemset:
            sumi=0
            for x in range(len(crimes)):
                mini=10000
                for y in kplusone_item:
                    mini=min(mini,crimes.iloc[x][y])
                sumi+=mini
            if sumi>=min_sup:
                sup[tuple(kplusone_item)]=sumi
                kplusone_itemset.append(kplusone_item)
        if(len(kplusone_itemset)==0):
           break
        #print(kplusone_itemset)
        freq_itemsets.append(kplusone_itemset)
        k=k+1
    return(freq_itemsets)

In [13]:
min_sup=0.35
freq_itemsets = apriori(min_sup)

crime = ["", "Murder", "Rape", "Foeticide", "Kidnapping and Abduction", "Abetment of suicide", "Exposure and abandonment", "Procuration of minor girls", "Selling of girls for prostitution", "Prohibition of child marriage act", "Other Crimes"]
for k_itemsets in freq_itemsets:
    for itemset in k_itemsets:
        print("[", end =" ")
        for item in itemset:
            print(crime[item]+", ", end =" ")
        print("]")

[ Murder,  ]
[ Rape,  ]
[ Foeticide,  ]
[ Kidnapping and Abduction,  ]
[ Abetment of suicide,  ]
[ Exposure and abandonment,  ]
[ Procuration of minor girls,  ]
[ Selling of girls for prostitution,  ]
[ Prohibition of child marriage act,  ]
[ Other Crimes,  ]
[ Rape,  Kidnapping and Abduction,  ]
[ Rape,  Exposure and abandonment,  ]
[ Murder,  Rape,  ]
[ Rape,  Other Crimes,  ]
[ Murder,  Kidnapping and Abduction,  ]
[ Murder,  Exposure and abandonment,  ]
[ Murder,  Other Crimes,  ]
[ Exposure and abandonment,  Other Crimes,  ]
[ Kidnapping and Abduction,  Other Crimes,  ]
[ Murder,  Rape,  Kidnapping and Abduction,  ]
[ Murder,  Rape,  Other Crimes,  ]

In [14]:
sup

{(1,): 1,
 (2,): 1,
 (3,): 1,
 (4,): 1,
 (5,): 1,
 (6,): 1,
 (7,): 1,
 (8,): 1,
 (9,): 1,
 (10,): 1,
 (2, 4): 0.580219148959293,
 (2, 6): 0.4543838608838025,
 (1, 2): 0.5866684799178904,
 (2, 10): 0.5740289642888715,
 (1, 4): 0.5141028333662461,
 (1, 6): 0.40736174091641153,
 (1, 10): 0.4390427861675423,
 (6, 10): 0.3935018729500918,
 (4, 10): 0.3906158700530138,
 (1, 2, 4): 0.40645214404886865,
 (1, 2, 10): 0.37588676267926363}

In [15]:
def get_rules(min_conf):
    rules = []
    for i in range(1,len(freq_itemsets)):
        for itemset in freq_itemsets[i]:
            #print(itemset)
            for j in range(1, len(itemset)):
                listx=list(itertools.combinations(itemset, j))
                for x in listx:
                    conf = sup[tuple(itemset)]/sup[tuple(x)]
                    x=set(x)
                    y=set(itemset).difference(x)
                    if conf>=min_conf:
                        print("conf of",tuple([x,y]),"=",conf)
                        rules.append(tuple([x,y]))
    return rules

In [16]:
min_conf=0.5
rules = get_rules(min_conf)

conf of ({2}, {4}) = 0.580219148959293
conf of ({4}, {2}) = 0.580219148959293
conf of ({1}, {2}) = 0.5866684799178904
conf of ({2}, {1}) = 0.5866684799178904
conf of ({2}, {10}) = 0.5740289642888715
conf of ({10}, {2}) = 0.5740289642888715
conf of ({1}, {4}) = 0.5141028333662461
conf of ({4}, {1}) = 0.5141028333662461
conf of ({1, 2}, {4}) = 0.6928140133005873
conf of ({1, 4}, {2}) = 0.7906047538923263
conf of ({2, 4}, {1}) = 0.7005148740400922
conf of ({1, 2}, {10}) = 0.6407140924494058
conf of ({1, 10}, {2}) = 0.8561506407164203
conf of ({2, 10}, {1}) = 0.6548219446468632

In [17]:
#finalrules = []
for rule in rules:
    #finalrule = []
    a = rule[0]
    b=rule[1]
    for elem in a:
        print(crime[elem]+", ", end=" ")
        #finalrule.append(crime[elem])
    print("--->", end=" ")
    #finalrule.append("--->")
    for elem in b:
        print(crime[elem]+", ", end=" ")
        #finalrule.append(crime[elem])
    #finalrules.append(finalrule)
    print()

Rape,  ---> Kidnapping and Abduction,
Kidnapping and Abduction,  ---> Rape,
Murder,  ---> Rape,
Rape,  ---> Murder,
Rape,  ---> Other Crimes,
Other Crimes,  ---> Rape,
Murder,  ---> Kidnapping and Abduction,
Kidnapping and Abduction,  ---> Murder,
Murder,  Rape,  ---> Kidnapping and Abduction,
Murder,  Kidnapping and Abduction,  ---> Rape,
Rape,  Kidnapping and Abduction,  ---> Murder,
Murder,  Rape,  ---> Other Crimes,
Murder,  Other Crimes,  ---> Rape,
Rape,  Other Crimes,  ---> Murder,